### PR TITLE
Use git to determine root and branch name

### PR DESCRIPTION
**Pull request by joshuachp**
Use the git command `root` to find the root directory and use `branch --show-current` for the branch name.

> Changed only the two functions, the rest is formatting.

### CODE REVIEW

**Comment by joshuachp** [comment]
Some local functions are not used and could be removed

**Comment by joshuachp** [comment]
Proposed here #92

**Comment by glepnir** [comment]
Using git command will start a git process. I'm thinking about performance issues here, so I don't use gitcommand, because the neovim statusline will be executed multiple times asynchronously.

**Comment by joshuachp** [comment]
The code before was using io.popen spawning a process for cd so my idea came from there. Also I had a problem with a custom `gitdir` so that was the main reason for using git in the first place.

**Comment by glepnir** [comment]
The current implementation is to enter the git directory to obtain branch information through refs folder, without using git commands

**Comment by joshuachp** [comment]
Yeh, I agre it has a performance impact. I'll try to fix the custom `gitdir` without spwaining a process.

**Comment by glepnir** [comment]
Anyway Thanks Pr.

**Pull request closed without merging**
