### PR TITLE
Fix gidir and use getcwd

### PR DESCRIPTION
**Pull request by joshuachp**
Make both `has_git_..` functions return the git directory or nil.  Use
the same check for all function and vim function `getcwd` instead of
opening another process.

### CODE REVIEW

**Comment by glepnir** [comment]
I found that you used 4 space indent for lua ?

**Comment by joshuachp** [comment]
Sorry the formatted picked up the mixed indentation. Thanks for telling me

**Comment by glepnir** [comment]
I will test it later. Thanks for PR

**Comment by glepnir** [comment]
merged.

**Pull request merged**
