### PR TITLE
feat(provider_vcs): Provide branch name for detached head.

### PR DESCRIPTION
**Pull request by sindrets**
This provides a branch name also when a git repo has a detached head.

### CODE REVIEW

**Comment by glepnir** [comment]
Thanks for pr. I want to know use only this way that use `git command` ? because the statusline will execute async. so it maybe will open many git thread?

**Comment by sindrets** [comment]
@glepnir well, after my last PR, when a branch name is found it is cached.

https://github.com/glepnir/galaxyline.nvim/blob/54b5ee9ba0a511fc73d426a20d8e8e2dd11654ae/lua/galaxyline/provider_vcs.lua#L158

So any subsequent calls to `get_git_branch` will simply return the value from the cache until `.git/HEAD` is modified.

https://github.com/glepnir/galaxyline.nvim/blob/54b5ee9ba0a511fc73d426a20d8e8e2dd11654ae/lua/galaxyline/provider_vcs.lua#L127-L133

> I want to know that is there only have one way ? use git command ?

When the head is detached the HEAD file simply contains a commit hash. This is the most efficient way that I am aware of to figure out where the head was detached from.

**Comment by glepnir** [comment]
I would like use this way :)

**Comment by sindrets** [comment]
I'm sorry, I'm a bit confused. What way would you like? I just described how it already works.

**Comment by sindrets** [comment]
@glepnir Could you please clarify?

**Comment by glepnir** [comment]
use a cache

**Comment by glepnir** [comment]
use a cache

**Comment by sindrets** [comment]
@glepnir Like I tried to explain: *I have already implemented a cache*.

This is what the cache looks like after one call to `get_git_branch` in a git repo with a detached head:

```lua
{
  ["/home/sindrets/Documents/git/nvim-tree.lua"] = {
    branch = "detached at upstream/master",
    head = "de93da78a9fd608a7b7c40e3b31ed17f61180eb7\n",
    mtime = 1617968450
  }
}
```

Now any subsequent calls to `get_git_branch` will get a cache hit and won't call `get_git_detached_head` until the HEAD file has been modified, causing the cache to be invalid. 

https://github.com/glepnir/galaxyline.nvim/blob/54b5ee9ba0a511fc73d426a20d8e8e2dd11654ae/lua/galaxyline/provider_vcs.lua#L127-L132

**Comment by glepnir** [comment]
LGTM

**Pull request merged**
