### PR TITLE
add argument of changing readonly and modified icon.

### PR DESCRIPTION
**Pull request by yamatsum**
# Description
add argument of changing readonly and modified icon.

## Type of change
- New feature (non-breaking change which adds functionality)

## Reference

### CODE REVIEW

**Comment by cloggier** [comment]
It would be good to add some documentation. Otherwise discoverability of this feature won't be too good.

**Comment by yamatsum** [comment]
Is the document added to the readme?
The following functions are also not described.
https://github.com/glepnir/galaxyline.nvim/blob/a6c2cbc2218cb2e59fd3353fb827da82b84a248a/lua/galaxyline/provider_extensions.lua#L28
Isn't it unnatural that there is only one explanation for the function?

**Comment by glepnir** [comment]
vista_nearest already in readme.

**Comment by glepnir** [comment]
about this change. I think it's better to add description in readme.

**Comment by yamatsum** [comment]
> vista_nearest already in readme.

There is a description, but there is no details about vista_icon. 
So get_current_file_name is already listed in the readme.

if add, I think should give details about all the functions you provide.

**Comment by yamatsum** [comment]
@glepnir

**Comment by yamatsum** [comment]
@glepnir 
Can you give me a review?

**Comment by glepnir** [comment]
LGTM

**Pull request merged**
