### PR TITLE
rewrite colorscheme

### PR DESCRIPTION
**Pull request by glepnir**
@Th3Whit3Wolf  Hi can you test this PR? I am not make sure this can work with your patch.

### CODE REVIEW

**Review by Th3Whit3Wolf — APPROVED** [review]
Yep still works!

**Comment by glepnir** [comment]
Did everything works fine?

**Comment by Th3Whit3Wolf** [comment]
Yeah, everything worked as expected.

**Comment by glepnir** [comment]
Thanks merge then.

**Pull request merged**
